spring.application.name=mue

# DB 정보 각자 로컬 환경에 맞게 변경
# 1. 아래 url, username, password 각자 로컬 환경에 맞게 변경해주세요
# 2. 설정 후 .gitignore 파일에 application.properties를 추가해주세요
#    (각자 업데이트한 DB 정보가 서로 꼬이지 않게 하기 위함입니다)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/practice_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=1012

# true로 설정 시 jpa 쿼리문 확인 가능
spring.jpa.show-sql=true

# DDL 정의시 DB의 고유 기능을 사용 가능
spring.jpa.hibernate.ddl-auto=update

# JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여줌
spring.jpa.properties.hibernate.format_sql=true